"""
PhantomFeed — Threat Actor Seed Data
50+ major APT groups, ransomware operators, and cybercriminal groups.
"""

THREAT_ACTORS = [
    # ── Russian APTs ────────────────────────────────────────────────────────────
    {
        "id": "apt28",
        "name": "APT28",
        "aliases": ["Fancy Bear", "Sofacy", "Pawn Storm", "STRONTIUM", "Forest Blizzard"],
        "origin": "Russia",
        "sponsor": "GRU",
        "motivation": "Espionage",
        "active_since": "2004",
        "target_industries": ["Government", "Defense", "NATO", "Political", "Media", "Energy"],
        "ttps": ["T1566.001", "T1078", "T1190", "T1486", "T1203", "T1027", "T1059.003"],
        "known_malware": ["X-Agent", "Sofacy", "Zebrocy", "GAMEFISH", "CHOPSTICK", "SOURFACE"],
        "description": "Russian GRU-sponsored group known for targeting NATO countries, political organizations, and defense contractors. Linked to DNC hack (2016), Olympic anti-doping agencies, and Ukrainian infrastructure attacks.",
        "recent_activity": "Active",
    },
    {
        "id": "apt29",
        "name": "APT29",
        "aliases": ["Cozy Bear", "Nobelium", "Midnight Blizzard", "The Dukes", "IRON HEMLOCK"],
        "origin": "Russia",
        "sponsor": "SVR",
        "motivation": "Espionage",
        "active_since": "2008",
        "target_industries": ["Government", "Defense", "Technology", "Healthcare", "NGOs", "Think Tanks"],
        "ttps": ["T1566.002", "T1195.002", "T1078", "T1550.001", "T1021.002", "T1560.001"],
        "known_malware": ["SUNBURST", "TEARDROP", "MagicWeb", "WellMess", "GraphicalNeutrino"],
        "description": "Russian SVR-sponsored elite cyber unit responsible for the SolarWinds supply chain attack (2020), Microsoft executive email breach (2024), and persistent targeting of Western governments and technology firms.",
        "recent_activity": "Active",
    },
    {
        "id": "sandworm",
        "name": "Sandworm",
        "aliases": ["Voodoo Bear", "IRIDIUM", "Seashell Blizzard", "Electrum"],
        "origin": "Russia",
        "sponsor": "GRU Unit 74455",
        "motivation": "Sabotage",
        "active_since": "2009",
        "target_industries": ["Energy", "Government", "Critical Infrastructure", "Defense", "Media"],
        "ttps": ["T1486", "T1561.002", "T1059.001", "T1190", "T1133", "T1078"],
        "known_malware": ["NotPetya", "BlackEnergy", "Industroyer", "CaddyWiper", "WhisperGate"],
        "description": "Russia's most destructive cyber unit, responsible for attacks on Ukrainian power grid (2015, 2016), NotPetya ransomware ($10B damages), and ongoing destructive attacks against Ukrainian civilian infrastructure.",
        "recent_activity": "Active",
    },
    {
        "id": "turla",
        "name": "Turla",
        "aliases": ["Snake", "Venomous Bear", "Secret Blizzard", "Waterbug", "KRYPTON"],
        "origin": "Russia",
        "sponsor": "FSB",
        "motivation": "Espionage",
        "active_since": "1996",
        "target_industries": ["Government", "Defense", "Military", "Embassies", "Research"],
        "ttps": ["T1566.001", "T1071.003", "T1102", "T1056.001", "T1218.011"],
        "known_malware": ["Snake/Uroburos", "Carbon", "Kazuar", "TinyTurla", "ComRAT"],
        "description": "One of the oldest and most sophisticated Russian APT groups, known for hijacking satellite internet links for C2, targeting embassies worldwide, and long-term persistent access operations.",
        "recent_activity": "Active",
    },
    # ── Chinese APTs ─────────────────────────────────────────────────────────────
    {
        "id": "apt41",
        "name": "APT41",
        "aliases": ["Double Dragon", "Winnti", "Barium", "WICKED PANDA", "Brass Typhoon"],
        "origin": "China",
        "sponsor": "MSS",
        "motivation": "Espionage / Financial",
        "active_since": "2012",
        "target_industries": ["Healthcare", "Technology", "Telecom", "Video Games", "Finance", "Government"],
        "ttps": ["T1195.002", "T1190", "T1078", "T1059.003", "T1486", "T1027"],
        "known_malware": ["ShadowPad", "PlugX", "KEYPLUG", "DEADEYE", "LOWKEY"],
        "description": "Unique dual-mission Chinese group conducting both state-sponsored espionage and financially motivated operations simultaneously. Linked to video game company compromises and supply chain attacks via software updates.",
        "recent_activity": "Active",
    },
    {
        "id": "apt10",
        "name": "APT10",
        "aliases": ["Stone Panda", "MenuPass", "Cicada", "Bronze Riverside", "Potassium"],
        "origin": "China",
        "sponsor": "MSS / Tianjin Bureau",
        "motivation": "Espionage",
        "active_since": "2009",
        "target_industries": ["MSP", "Healthcare", "Government", "Defense", "Finance", "Aerospace"],
        "ttps": ["T1190", "T1078", "T1021.001", "T1059.001", "T1560.001", "T1071.001"],
        "known_malware": ["PlugX", "QuasarRAT", "ChChes", "RedLeaves", "UPPERCUT"],
        "description": "Chinese group known for Operation Cloud Hopper — compromising managed service providers to pivot into their clients' networks. DOJ indicted two MSS officers in 2018 for targeting 12+ countries.",
        "recent_activity": "Active",
    },
    {
        "id": "volt_typhoon",
        "name": "Volt Typhoon",
        "aliases": ["Bronze Silhouette", "Vanguard Panda", "Dev-0391"],
        "origin": "China",
        "sponsor": "PLA",
        "motivation": "Pre-positioning",
        "active_since": "2021",
        "target_industries": ["Critical Infrastructure", "Energy", "Water", "Ports", "Communications", "Military"],
        "ttps": ["T1190", "T1133", "T1078", "T1021.001", "T1070.004", "T1505.003"],
        "known_malware": ["KV-botnet", "LOTL (LOLBins)", "Custom web shells"],
        "description": "Chinese state group focused on pre-positioning in US critical infrastructure for potential disruption during conflict over Taiwan. Uses living-off-the-land techniques to evade detection. FBI/CISA issued emergency advisory in 2024.",
        "recent_activity": "Active",
    },
    {
        "id": "apt40",
        "name": "APT40",
        "aliases": ["BRONZE MOHAWK", "Temp.Periscope", "Leviathan", "GADOLINIUM", "Kryptonite Panda"],
        "origin": "China",
        "sponsor": "MSS / Hainan State Security Department",
        "motivation": "Espionage",
        "active_since": "2013",
        "target_industries": ["Maritime", "Defense", "Aviation", "Government", "Research", "Technology"],
        "ttps": ["T1566.002", "T1190", "T1059.001", "T1505.003", "T1102", "T1560.001"],
        "known_malware": ["SCANBOX", "AIRBREAK", "FRESHAIR", "PHOTO", "HOMEFRY"],
        "description": "Chinese MSS-linked group targeting maritime, naval defense, and aviation sectors. DOJ indicted four MSS officers in 2021. Active in Pacific region targeting COVID-19 research during pandemic.",
        "recent_activity": "Active",
    },
    # ── North Korean APTs ─────────────────────────────────────────────────────────
    {
        "id": "lazarus",
        "name": "Lazarus Group",
        "aliases": ["Hidden Cobra", "Zinc", "Diamond Sleet", "TEMP.Hermit", "Guardians of Peace"],
        "origin": "North Korea",
        "sponsor": "RGB (Reconnaissance General Bureau)",
        "motivation": "Financial / Espionage / Sabotage",
        "active_since": "2009",
        "target_industries": ["Finance", "Cryptocurrency", "Defense", "Government", "Media", "Healthcare"],
        "ttps": ["T1566.001", "T1195.002", "T1486", "T1055", "T1059.003", "T1027"],
        "known_malware": ["HOPLIGHT", "ELECTRICFISH", "AppleJeus", "DTrack", "MagicRAT", "LPEClient"],
        "description": "North Korea's primary cyber unit responsible for Sony Pictures hack (2014), SWIFT banking attacks ($81M Bangladesh Bank heist), WannaCry (2017), and billions stolen from crypto exchanges to fund WMD programs.",
        "recent_activity": "Active",
    },
    {
        "id": "kimsuky",
        "name": "Kimsuky",
        "aliases": ["Thallium", "Black Banshee", "Emerald Sleet", "VELVET CHOLLIMA"],
        "origin": "North Korea",
        "sponsor": "RGB",
        "motivation": "Espionage",
        "active_since": "2012",
        "target_industries": ["Government", "Think Tanks", "Research", "Defense", "Nuclear", "Media"],
        "ttps": ["T1566.001", "T1566.002", "T1078", "T1059.001", "T1071.001"],
        "known_malware": ["BabyShark", "FlowerPower", "GoldDragon", "AppleSeed", "RandomQuery"],
        "description": "North Korean intelligence-gathering unit focused on Korean Peninsula policy, nuclear nonproliferation research, and sanctions information. Known for spear-phishing campaigns targeting think tanks and policy researchers.",
        "recent_activity": "Active",
    },
    {
        "id": "apt38",
        "name": "APT38",
        "aliases": ["Nickel Gladstone", "BeagleBoyz", "SWIFT Heist Group"],
        "origin": "North Korea",
        "sponsor": "RGB",
        "motivation": "Financial",
        "active_since": "2014",
        "target_industries": ["Finance", "Banking", "SWIFT Network"],
        "ttps": ["T1566.001", "T1059.001", "T1057", "T1070", "T1485"],
        "known_malware": ["BLINDINGCAN", "CROWDEDFLOUNDER", "FASTCASH", "ELECTRICFISH"],
        "description": "North Korean subunit specializing in financial system intrusions, particularly targeting SWIFT interbank messaging system. Responsible for over $2B in theft from financial institutions across 38 countries.",
        "recent_activity": "Active",
    },
    # ── Iranian APTs ──────────────────────────────────────────────────────────────
    {
        "id": "apt33",
        "name": "APT33",
        "aliases": ["Refined Kitten", "Elfin", "Holmium", "Peach Sandstorm", "COBALT TRINITY"],
        "origin": "Iran",
        "sponsor": "IRGC",
        "motivation": "Espionage / Sabotage",
        "active_since": "2013",
        "target_industries": ["Aerospace", "Defense", "Energy", "Government", "Chemical"],
        "ttps": ["T1566.001", "T1078", "T1133", "T1059.001", "T1486", "T1529"],
        "known_malware": ["SHAPESHIFT", "DropShot", "StoneDrill", "TURNEDUP", "NANOCORE"],
        "description": "Iranian IRGC-linked group targeting Saudi Arabian organizations and US aerospace. Known for destructive Shamoon variants and password spraying campaigns targeting defense contractors.",
        "recent_activity": "Active",
    },
    {
        "id": "apt34",
        "name": "APT34",
        "aliases": ["OilRig", "Helix Kitten", "Crambus", "Hazel Sandstorm", "COBALT GYPSY"],
        "origin": "Iran",
        "sponsor": "MOIS",
        "motivation": "Espionage",
        "active_since": "2014",
        "target_industries": ["Government", "Finance", "Energy", "Telecom", "Chemical", "Healthcare"],
        "ttps": ["T1566.001", "T1190", "T1059.001", "T1505.003", "T1071.004", "T1048"],
        "known_malware": ["POWRUNER", "BONDUPDATER", "QUADAGENT", "RANGO", "Saitama"],
        "description": "Iranian Ministry of Intelligence group targeting Middle Eastern government and critical infrastructure. Known for DNS tunneling for C2 communications and targeting telecommunications providers.",
        "recent_activity": "Active",
    },
    {
        "id": "charming_kitten",
        "name": "Charming Kitten",
        "aliases": ["APT35", "Phosphorus", "Mint Sandstorm", "TA453", "COBALT ILLUSION"],
        "origin": "Iran",
        "sponsor": "IRGC",
        "motivation": "Espionage",
        "active_since": "2014",
        "target_industries": ["Media", "Government", "Human Rights", "Academic", "Healthcare", "Nuclear"],
        "ttps": ["T1566.001", "T1598.003", "T1078", "T1539", "T1056.003"],
        "known_malware": ["POWERSTAR", "GorjolEcho", "CharmPower", "BASICSTAR", "MEDIAPIE"],
        "description": "Iranian intelligence group known for credential harvesting against journalists, academics, and policy researchers. Used fake conference invitations and impersonated think tank researchers. Targeted COVID-19 vaccine research.",
        "recent_activity": "Active",
    },
    # ── Ransomware Groups ─────────────────────────────────────────────────────────
    {
        "id": "lockbit",
        "name": "LockBit",
        "aliases": ["LockBit 3.0", "LockBit Black", "ABCD"],
        "origin": "Russia/Eastern Europe",
        "sponsor": "Cybercriminal",
        "motivation": "Financial",
        "active_since": "2019",
        "target_industries": ["All Sectors", "Healthcare", "Government", "Finance", "Manufacturing"],
        "ttps": ["T1486", "T1566.001", "T1190", "T1078", "T1021.001", "T1562.001"],
        "known_malware": ["LockBit ransomware", "StealBit exfiltration tool"],
        "description": "World's most prolific ransomware gang (2022-2024) with RaaS model. Responsible for 25%+ of all ransomware incidents. Disrupted by Operation Cronos (Feb 2024) but resumed operations. Targets any sector with >$1M revenue.",
        "recent_activity": "Active",
    },
    {
        "id": "blackcat_alphv",
        "name": "BlackCat (ALPHV)",
        "aliases": ["ALPHV", "Noberus"],
        "origin": "Russia/Eastern Europe",
        "sponsor": "Cybercriminal",
        "motivation": "Financial",
        "active_since": "2021",
        "target_industries": ["Healthcare", "Finance", "Energy", "Legal", "Technology"],
        "ttps": ["T1486", "T1190", "T1078.003", "T1021.001", "T1562.001", "T1071.001"],
        "known_malware": ["ALPHV ransomware (Rust)", "ExMatter", "Karakurt exfil"],
        "description": "Sophisticated RaaS written in Rust. Responsible for Change Healthcare attack (Feb 2024) causing $22B+ in healthcare disruption across the US. FBI seized infrastructure in Dec 2023 but group resumed. Now reportedly disbanded.",
        "recent_activity": "Low Activity",
    },
    {
        "id": "cl0p",
        "name": "Cl0p",
        "aliases": ["TA505", "CLOP", "Lace Tempest"],
        "origin": "Russia/Ukraine",
        "sponsor": "Cybercriminal",
        "motivation": "Financial",
        "active_since": "2019",
        "target_industries": ["Finance", "Healthcare", "Technology", "Government", "Education"],
        "ttps": ["T1190", "T1059.001", "T1486", "T1537", "T1048.002"],
        "known_malware": ["Cl0p ransomware", "SDBot", "FlawedGrace"],
        "description": "Ransomware group known for mass exploitation of zero-days in file transfer software. Exploited MOVEit Transfer (2023), GoAnywhere MFT, and Accellion FTA vulnerabilities to breach 1000+ organizations simultaneously.",
        "recent_activity": "Active",
    },
    {
        "id": "rhysida",
        "name": "Rhysida",
        "aliases": ["Vice Society successor"],
        "origin": "Unknown",
        "sponsor": "Cybercriminal",
        "motivation": "Financial",
        "active_since": "2023",
        "target_industries": ["Healthcare", "Education", "Government", "Manufacturing"],
        "ttps": ["T1566.001", "T1190", "T1486", "T1078", "T1021.001"],
        "known_malware": ["Rhysida ransomware", "Cobalt Strike"],
        "description": "Emerging ransomware group with self-described 'cybersecurity team' branding. Responsible for British Library attack (2023) and Chilean Army breach. Exploits valid accounts and VPN vulnerabilities for initial access.",
        "recent_activity": "Active",
    },
    {
        "id": "play_ransomware",
        "name": "Play",
        "aliases": ["PlayCrypt", "Balloonfly"],
        "origin": "Russia",
        "sponsor": "Cybercriminal",
        "motivation": "Financial",
        "active_since": "2022",
        "target_industries": ["Government", "Manufacturing", "Healthcare", "Finance", "Critical Infrastructure"],
        "ttps": ["T1190", "T1078", "T1486", "T1021.002", "T1562.001"],
        "known_malware": ["Play ransomware", "Cobalt Strike", "SystemBC"],
        "description": "Ransomware group known for double extortion and targeting of MSPs to reach downstream victims. Active in US, Europe, and Latin America. Known for exploiting FortiOS and Exchange vulnerabilities.",
        "recent_activity": "Active",
    },
    {
        "id": "akira",
        "name": "Akira",
        "aliases": [],
        "origin": "Russia/Eastern Europe",
        "sponsor": "Cybercriminal",
        "motivation": "Financial",
        "active_since": "2023",
        "target_industries": ["Finance", "Manufacturing", "Technology", "Healthcare", "Education"],
        "ttps": ["T1190", "T1078", "T1486", "T1021.002", "T1562.001"],
        "known_malware": ["Akira ransomware (C++/Rust)", "Megazord"],
        "description": "Fast-growing ransomware group targeting Cisco VPN vulnerabilities (CVE-2023-20269) for initial access. Known for retro-aesthetic dark web leak site. Netted $42M in first year of operations.",
        "recent_activity": "Active",
    },
    # ── Hacktivism & Others ───────────────────────────────────────────────────────
    {
        "id": "scattered_spider",
        "name": "Scattered Spider",
        "aliases": ["UNC3944", "Starfraud", "Octo Tempest", "0ktapus"],
        "origin": "US/UK",
        "sponsor": "Cybercriminal",
        "motivation": "Financial",
        "active_since": "2022",
        "target_industries": ["Technology", "Telecom", "Hospitality", "Finance", "Gaming"],
        "ttps": ["T1566.001", "T1598.003", "T1621", "T1078", "T1531", "T1486"],
        "known_malware": ["ALPHV/BlackCat (affiliate)", "Cobalt Strike"],
        "description": "English-speaking cybercriminal group (average age ~20) known for sophisticated social engineering of IT help desks. Responsible for MGM Resorts ($100M+ loss), Caesars Entertainment, and Twilio/Okta supply chain attacks.",
        "recent_activity": "Active",
    },
    {
        "id": "lapsus",
        "name": "LAPSUS$",
        "aliases": ["DEV-0537", "Strawberry Tempest"],
        "origin": "Brazil/UK",
        "sponsor": "Cybercriminal",
        "motivation": "Financial / Notoriety",
        "active_since": "2021",
        "target_industries": ["Technology", "Telecom", "Gaming", "Automotive"],
        "ttps": ["T1598.003", "T1078", "T1531", "T1539", "T1552.001"],
        "known_malware": ["No custom malware — credential theft focus"],
        "description": "Teen-led extortion group that breached Microsoft, Nvidia, Samsung, Okta, Ubisoft, and Rockstar Games using SIM swapping and social engineering. Members arrested in UK and Brazil in 2022.",
        "recent_activity": "Dormant",
    },
    {
        "id": "killnet",
        "name": "Killnet",
        "aliases": ["KillMilk"],
        "origin": "Russia",
        "sponsor": "Pro-Russian hacktivist",
        "motivation": "Political / Ideological",
        "active_since": "2022",
        "target_industries": ["Government", "Healthcare", "Finance", "Critical Infrastructure", "NATO"],
        "ttps": ["T1498.001", "T1498.002", "T1659"],
        "known_malware": ["Custom DDoS tools", "Killnet botnet"],
        "description": "Pro-Russian hacktivist collective conducting DDoS attacks against NATO countries, US hospitals, and European government websites in response to support for Ukraine. Primarily disruptive rather than destructive.",
        "recent_activity": "Active",
    },
    # ── More APTs ─────────────────────────────────────────────────────────────────
    {
        "id": "apt1",
        "name": "APT1",
        "aliases": ["Comment Crew", "Shanghai Group", "Comment Panda"],
        "origin": "China",
        "sponsor": "PLA Unit 61398",
        "motivation": "Espionage",
        "active_since": "2006",
        "target_industries": ["Aerospace", "Defense", "Energy", "Finance", "IT", "Telecom"],
        "ttps": ["T1566.001", "T1059.003", "T1078", "T1560.001", "T1071.001"],
        "known_malware": ["WEBC2", "BISCUIT", "GreenCat", "SEASALT"],
        "description": "First widely documented Chinese APT, exposed by Mandiant in 2013. PLA Unit 61398 responsible for stealing terabytes of data from 141+ organizations across 20 industries over 7+ years.",
        "recent_activity": "Low Activity",
    },
    {
        "id": "fin7",
        "name": "FIN7",
        "aliases": ["Carbanak Group", "Navigator Group", "ELBRUS"],
        "origin": "Russia/Ukraine",
        "sponsor": "Cybercriminal",
        "motivation": "Financial",
        "active_since": "2013",
        "target_industries": ["Retail", "Hospitality", "Restaurant", "Finance"],
        "ttps": ["T1566.001", "T1059.001", "T1078", "T1486", "T1056.001"],
        "known_malware": ["Carbanak", "BIRDDOG", "BOOSTWRITE", "REvil (affiliate)", "DarkMatter"],
        "description": "Criminal group responsible for over $3B in theft from financial institutions and retail chains via POS malware and spear-phishing. Evolved to ransomware operations. Multiple members indicted by DOJ.",
        "recent_activity": "Active",
    },
    {
        "id": "equation_group",
        "name": "Equation Group",
        "aliases": ["Tilded Team", "UNITEDRAKE"],
        "origin": "USA",
        "sponsor": "NSA/TAO",
        "motivation": "Espionage",
        "active_since": "2001",
        "target_industries": ["Government", "Military", "Nuclear", "Telecom", "Finance", "Energy"],
        "ttps": ["T1195.002", "T1542.003", "T1059.003", "T1027", "T1102"],
        "known_malware": ["DOUBLEPULSAR", "ETERNALBLUE", "GRAYFISH", "FANNY", "EQUATIONDRUG"],
        "description": "Considered the most sophisticated threat actor ever discovered (Kaspersky, 2015). Tools including EternalBlue were later stolen by Shadow Brokers and repurposed in WannaCry/NotPetya attacks.",
        "recent_activity": "Unknown",
    },
    {
        "id": "sea_turtle",
        "name": "Sea Turtle",
        "aliases": ["SILICON", "Cosmic Wolf", "UNC1326"],
        "origin": "Turkey",
        "sponsor": "State-sponsored (likely MIT)",
        "motivation": "Espionage",
        "active_since": "2017",
        "target_industries": ["Government", "Military", "Energy", "Think Tanks", "NGOs", "ISP"],
        "ttps": ["T1584.002", "T1071.004", "T1040", "T1557.001"],
        "known_malware": ["SnappyTCP"],
        "description": "Turkish threat actor known for DNS hijacking attacks targeting government ministries, embassies, and ISPs across the Middle East and North Africa. Intercepts DNS queries to steal credentials.",
        "recent_activity": "Active",
    },
    {
        "id": "comet_chollima",
        "name": "Andariel",
        "aliases": ["Comet Chollima", "Silent Chollima", "PLUTONIUM", "DarkSeoul"],
        "origin": "North Korea",
        "sponsor": "RGB Cyber Operations",
        "motivation": "Financial / Espionage",
        "active_since": "2015",
        "target_industries": ["Defense", "Government", "Finance", "Healthcare", "Critical Infrastructure"],
        "ttps": ["T1566.001", "T1190", "T1059.001", "T1486", "T1078"],
        "known_malware": ["Maui ransomware", "H0lyGh0st", "DTrack", "Andarat"],
        "description": "North Korean subgroup of Lazarus focused on financially motivated attacks against South Korean defense and healthcare organizations. Responsible for Maui ransomware attacks targeting US healthcare in 2021-2022.",
        "recent_activity": "Active",
    },
    {
        "id": "hafnium",
        "name": "Hafnium",
        "aliases": ["Dev-0234", "Silk Typhoon"],
        "origin": "China",
        "sponsor": "MSS",
        "motivation": "Espionage",
        "active_since": "2019",
        "target_industries": ["Defense", "Research", "NGOs", "Law Firms", "Think Tanks", "Government"],
        "ttps": ["T1190", "T1505.003", "T1560.001", "T1021.001", "T1078"],
        "known_malware": ["China Chopper", "ASPXSPY", "ProxyLogon exploits"],
        "description": "Chinese MSS group responsible for zero-day exploitation of Microsoft Exchange (ProxyLogon, CVE-2021-26855) compromising 250,000+ servers globally in early 2021. Targets US-based defense contractors and policy research organizations.",
        "recent_activity": "Active",
    },
    {
        "id": "muddywater",
        "name": "MuddyWater",
        "aliases": ["MERCURY", "Seedworm", "Static Kitten", "Mango Sandstorm"],
        "origin": "Iran",
        "sponsor": "MOIS",
        "motivation": "Espionage",
        "active_since": "2017",
        "target_industries": ["Government", "Telecom", "Defense", "Energy", "Healthcare"],
        "ttps": ["T1566.001", "T1059.001", "T1071.001", "T1021.002", "T1078"],
        "known_malware": ["POWERSTATS", "Canopy", "PhonyC2", "BugSleep"],
        "description": "Iranian MOIS subordinate element conducting espionage against Middle Eastern governments. Known for using legitimate remote administration tools (ScreenConnect, RemoteUtilities) to blend with normal network traffic.",
        "recent_activity": "Active",
    },
    {
        "id": "wizard_spider",
        "name": "Wizard Spider",
        "aliases": ["UNC1878", "Gold Blackburn", "TEMP.MixMaster"],
        "origin": "Russia",
        "sponsor": "Cybercriminal",
        "motivation": "Financial",
        "active_since": "2016",
        "target_industries": ["Healthcare", "Finance", "Government", "Manufacturing", "Education"],
        "ttps": ["T1566.001", "T1059.003", "T1486", "T1489", "T1078"],
        "known_malware": ["TrickBot", "Ryuk", "Conti", "BazarLoader"],
        "description": "Russian cybercriminal group responsible for TrickBot banking trojan and Ryuk ransomware. Targeted US hospitals during COVID-19 pandemic (2020). Core members believed to have transitioned to other groups after law enforcement pressure.",
        "recent_activity": "Restructured",
    },
    {
        "id": "conti",
        "name": "Conti",
        "aliases": ["Wizard Spider successor", "GOLD ULRICK"],
        "origin": "Russia",
        "sponsor": "Cybercriminal",
        "motivation": "Financial",
        "active_since": "2020",
        "target_industries": ["Healthcare", "Critical Infrastructure", "Government", "Finance"],
        "ttps": ["T1486", "T1078", "T1021.002", "T1562.001", "T1537"],
        "known_malware": ["Conti ransomware", "BazarLoader", "Cobalt Strike"],
        "description": "Prolific ransomware group that earned $2.7B before disbanding in 2022 after internal chat logs were leaked by Ukrainian member. Responsible for Irish HSE attack shutting down national health system. Members spun off into Black Basta, Royal, and other groups.",
        "recent_activity": "Defunct",
    },
    {
        "id": "black_basta",
        "name": "Black Basta",
        "aliases": ["Cardinal"],
        "origin": "Russia",
        "sponsor": "Cybercriminal",
        "motivation": "Financial",
        "active_since": "2022",
        "target_industries": ["Healthcare", "Manufacturing", "Finance", "Construction", "Legal"],
        "ttps": ["T1566.001", "T1190", "T1486", "T1021.002", "T1562.001"],
        "known_malware": ["Black Basta ransomware", "BRUTED", "Cobalt Strike"],
        "description": "Conti splinter group that became one of the most active ransomware operators in 2023-2024. Responsible for Ascension Health attack (2024) disrupting care at 140 hospitals. Uses QakBot for initial access.",
        "recent_activity": "Active",
    },
    {
        "id": "indrik_spider",
        "name": "Indrik Spider",
        "aliases": ["Evil Corp", "Gold Drake", "Dudear"],
        "origin": "Russia",
        "sponsor": "Cybercriminal (OFAC sanctioned)",
        "motivation": "Financial",
        "active_since": "2014",
        "target_industries": ["Finance", "Banking", "Healthcare", "Government"],
        "ttps": ["T1566.001", "T1059.003", "T1486", "T1078", "T1040"],
        "known_malware": ["Dridex", "BitPaymer", "WastedLocker", "Hades", "Phoenix Locker"],
        "description": "Russian cybercriminal group sanctioned by OFAC in 2019. Led by Maksim Yakubets. Responsible for Dridex banking trojan and multiple ransomware families. Deliberately changed ransomware brands to evade sanctions on ransom payments.",
        "recent_activity": "Active",
    },
    {
        "id": "darkside",
        "name": "DarkSide",
        "aliases": ["Carbon Spider successor"],
        "origin": "Russia",
        "sponsor": "Cybercriminal",
        "motivation": "Financial",
        "active_since": "2020",
        "target_industries": ["Energy", "Finance", "Technology", "Manufacturing"],
        "ttps": ["T1486", "T1190", "T1078", "T1021.001", "T1537"],
        "known_malware": ["DarkSide ransomware"],
        "description": "RaaS group responsible for Colonial Pipeline attack (May 2021) causing US fuel shortage and $4.4M ransom. Shut down operations one week later under US government pressure. Core team reportedly reformed as BlackMatter.",
        "recent_activity": "Defunct",
    },
    {
        "id": "rEvil",
        "name": "REvil",
        "aliases": ["Sodinokibi", "Gold Southfield"],
        "origin": "Russia",
        "sponsor": "Cybercriminal",
        "motivation": "Financial",
        "active_since": "2019",
        "target_industries": ["All Sectors", "Finance", "Healthcare", "Legal", "Technology"],
        "ttps": ["T1486", "T1195.002", "T1078", "T1566.001", "T1490"],
        "known_malware": ["REvil/Sodinokibi ransomware"],
        "description": "Prolific Russian RaaS group responsible for Kaseya VSA supply chain attack (2021, 1500+ businesses), JBS Foods ($11M ransom), and Travelex. FSB arrested 14 members in January 2022 in unprecedented Russian law enforcement action.",
        "recent_activity": "Defunct",
    },
    {
        "id": "trickbot",
        "name": "TrickBot Gang",
        "aliases": ["ITG23", "Gold Blackburn"],
        "origin": "Russia/Ukraine",
        "sponsor": "Cybercriminal",
        "motivation": "Financial",
        "active_since": "2016",
        "target_industries": ["Finance", "Healthcare", "Government", "Technology"],
        "ttps": ["T1566.001", "T1059.003", "T1021.002", "T1486", "T1078"],
        "known_malware": ["TrickBot", "BazarLoader", "Anchor", "Emotet (distribution)"],
        "description": "Operator of TrickBot banking trojan — one of the most prevalent malware platforms. Served as initial access broker for Ryuk and Conti ransomware. Servers disrupted by Microsoft/ESET in October 2020 but quickly rebuilt.",
        "recent_activity": "Restructured",
    },
    {
        "id": "transparent_tribe",
        "name": "Transparent Tribe",
        "aliases": ["APT36", "ProjectM", "Mythic Leopard", "COPPER FIELDSTONE"],
        "origin": "Pakistan",
        "sponsor": "State-sponsored",
        "motivation": "Espionage",
        "active_since": "2013",
        "target_industries": ["Government", "Military", "Defense", "Education"],
        "ttps": ["T1566.001", "T1566.002", "T1059.001", "T1078", "T1027"],
        "known_malware": ["CrimsonRAT", "CAPRAT", "ObliqueRAT", "ElizaRAT"],
        "description": "Pakistani state-sponsored group primarily targeting Indian government, military, and defense research. Known for weaponized documents and Android malware targeting Indian defense personnel.",
        "recent_activity": "Active",
    },
    {
        "id": "lazarus_bluenoroff",
        "name": "BlueNoroff",
        "aliases": ["TA444", "Stardust Chollima", "NICKEL GLADSTONE"],
        "origin": "North Korea",
        "sponsor": "RGB",
        "motivation": "Financial",
        "active_since": "2016",
        "target_industries": ["Cryptocurrency", "DeFi", "FinTech", "Banking", "Venture Capital"],
        "ttps": ["T1566.001", "T1195.002", "T1059.001", "T1027", "T1041"],
        "known_malware": ["AppleJeus", "RustBucket", "KANDYKORN", "ObjCShellz"],
        "description": "Lazarus subgroup focused exclusively on financial theft from crypto exchanges, DeFi protocols, and VC firms. Responsible for $625M Axie Infinity/Ronin Network hack (2022) and Harmony Bridge exploit ($100M).",
        "recent_activity": "Active",
    },
    {
        "id": "silence_group",
        "name": "Silence Group",
        "aliases": ["WHISPER SPIDER", "Gold Franklin"],
        "origin": "Russia",
        "sponsor": "Cybercriminal",
        "motivation": "Financial",
        "active_since": "2016",
        "target_industries": ["Banking", "Finance", "Insurance"],
        "ttps": ["T1566.001", "T1059.003", "T1059.001", "T1056.001"],
        "known_malware": ["Silence framework", "EmpireDNSAgent", "ProxyBot"],
        "description": "Sophisticated Russian financial threat group targeting ATM networks and bank card processing centers in Russia, Eastern Europe, and Asia. Members reportedly former cybersecurity professionals and penetration testers.",
        "recent_activity": "Active",
    },
    {
        "id": "gamaredon",
        "name": "Gamaredon",
        "aliases": ["Primitive Bear", "ACTINIUM", "Armageddon", "Shuckworm"],
        "origin": "Russia",
        "sponsor": "FSB",
        "motivation": "Espionage",
        "active_since": "2013",
        "target_industries": ["Government", "Military", "Defense", "NGOs"],
        "ttps": ["T1566.001", "T1059.001", "T1071.001", "T1105", "T1091"],
        "known_malware": ["Pterodo/Gamaredon", "BoneSpy", "PlainGnome", "Giddome"],
        "description": "Russian FSB group almost exclusively targeting Ukrainian government and military. Dramatically increased operations following 2022 invasion. Known for high-volume spear-phishing and USB-borne malware.",
        "recent_activity": "Active",
    },
    {
        "id": "groundpete",
        "name": "TA4903",
        "aliases": ["Spear-Phishing BEC group"],
        "origin": "Unknown",
        "sponsor": "Cybercriminal",
        "motivation": "Financial",
        "active_since": "2022",
        "target_industries": ["Government", "Finance", "Construction", "Healthcare"],
        "ttps": ["T1566.002", "T1534", "T1078", "T1550.002"],
        "known_malware": ["Phishing infrastructure"],
        "description": "Business Email Compromise (BEC) group targeting US federal agencies and private sector. Impersonates government entities to divert vendor payments. Uses QR codes to bypass email security filters.",
        "recent_activity": "Active",
    },
    {
        "id": "lockergoga",
        "name": "TEMP.Veles",
        "aliases": ["Triton/TRISIS Actor", "XENOTIME"],
        "origin": "Russia",
        "sponsor": "CNIIHM (Russian state institute)",
        "motivation": "Sabotage",
        "active_since": "2014",
        "target_industries": ["Oil and Gas", "Petrochemical", "Critical Infrastructure", "ICS/OT"],
        "ttps": ["T1190", "T1059.003", "T1542.005", "T1046"],
        "known_malware": ["TRITON/TRISIS (targets Schneider Electric Triconex safety systems)"],
        "description": "Created TRITON malware specifically designed to disable industrial safety systems (Triconex) at Saudi Aramco facility (2017). First malware designed to directly kill humans by disabling safety shutoffs. Linked to Russian CNIIHM institute.",
        "recent_activity": "Low Activity",
    },
    {
        "id": "fancy_bear_gru_85",
        "name": "GRU Unit 26165",
        "aliases": ["APT28 (specific unit)", "Sofacy"],
        "origin": "Russia",
        "sponsor": "GRU",
        "motivation": "Espionage / Sabotage",
        "active_since": "2004",
        "target_industries": ["Political", "Government", "Defense", "Olympics", "NATO"],
        "ttps": ["T1566.001", "T1203", "T1078", "T1486"],
        "known_malware": ["X-Agent", "CHOPSTICK", "GAMEFISH"],
        "description": "The specific GRU unit behind APT28 operations including DNC hack (2016), WADA/anti-doping attacks, and French election interference. 7 officers indicted by DOJ in 2018.",
        "recent_activity": "Active",
    },
    {
        "id": "evilnum",
        "name": "Evilnum",
        "aliases": ["DeathStalker", "PowerSing"],
        "origin": "Unknown (likely mercenary)",
        "sponsor": "Mercenary/Hack-for-hire",
        "motivation": "Financial (espionage for hire)",
        "active_since": "2018",
        "target_industries": ["Finance", "FinTech", "Crypto", "Legal", "Investment"],
        "ttps": ["T1566.001", "T1566.002", "T1059.001", "T1027", "T1539"],
        "known_malware": ["EVILNUM", "PyVil RAT", "TerracTV", "PowerPepper"],
        "description": "Hack-for-hire group targeting financial services and FinTech companies. Steals financial data, customer information, and trading algorithms. Believed to be a mercenary operation serving multiple clients.",
        "recent_activity": "Active",
    },
    {
        "id": "ta505",
        "name": "TA505",
        "aliases": ["Hive0065", "GRACEFUL SPIDER", "Gold Tahoe"],
        "origin": "Russia",
        "sponsor": "Cybercriminal",
        "motivation": "Financial",
        "active_since": "2014",
        "target_industries": ["Finance", "Retail", "Healthcare", "Education"],
        "ttps": ["T1566.001", "T1059.003", "T1059.001", "T1486"],
        "known_malware": ["Dridex", "Locky", "GlobeImposter", "FlawedAmmyy", "SDBbot"],
        "description": "High-volume spam-based threat actor responsible for distributing some of the world's most prevalent banking trojans and ransomware. Known for seasonal campaign surges and targeting financial sector with Dridex.",
        "recent_activity": "Active",
    },
    {
        "id": "cozy_bear_solarwinds",
        "name": "UNC2452",
        "aliases": ["StellarParticle", "Dark Halo", "SolarStorm"],
        "origin": "Russia",
        "sponsor": "SVR",
        "motivation": "Espionage",
        "active_since": "2020",
        "target_industries": ["Government", "Technology", "Defense", "Consulting"],
        "ttps": ["T1195.002", "T1078.004", "T1558.001", "T1550.001"],
        "known_malware": ["SUNBURST", "SUNSPOT", "TEARDROP", "RAINDROP"],
        "description": "Specific SolarWinds campaign cluster (likely APT29) that compromised the SolarWinds Orion supply chain, deploying SUNBURST backdoor to 18,000+ organizations including US Treasury, DOJ, DHS, and Microsoft.",
        "recent_activity": "Merged into APT29",
    },
    {
        "id": "gold_melody",
        "name": "Prophet Spider",
        "aliases": ["Gold Melody", "UNC961"],
        "origin": "Unknown",
        "sponsor": "Cybercriminal (Initial Access Broker)",
        "motivation": "Financial",
        "active_since": "2019",
        "target_industries": ["All sectors (access broker)"],
        "ttps": ["T1190", "T1505.003", "T1071.001", "T1078"],
        "known_malware": ["WebLogic exploits", "various web shells"],
        "description": "Initial access broker that compromises internet-facing servers (Oracle WebLogic, VMware, Sitecore) and sells access to ransomware affiliates. Operates entirely within the initial access phase.",
        "recent_activity": "Active",
    },
    {
        "id": "apt32",
        "name": "APT32",
        "aliases": ["OceanLotus", "SeaLotus", "Cobalt Kitty", "Ocean Buffalo"],
        "origin": "Vietnam",
        "sponsor": "Vietnamese government",
        "motivation": "Espionage",
        "active_since": "2012",
        "target_industries": ["Government", "Media", "Research", "Automotive", "Healthcare", "Civil Society"],
        "ttps": ["T1566.001", "T1059.001", "T1078", "T1105", "T1071.001"],
        "known_malware": ["WINDSHIELD", "KOMPROGO", "SOUNDBITE", "KerrDown", "Denis"],
        "description": "Vietnamese government-linked APT targeting foreign governments and companies in Southeast Asia, particularly around the South China Sea dispute. Also targeted BMW and Hyundai automotive companies.",
        "recent_activity": "Active",
    },
    {
        "id": "carbanak",
        "name": "Carbanak",
        "aliases": ["ANUNAK", "FIN7 overlap"],
        "origin": "Russia/Ukraine",
        "sponsor": "Cybercriminal",
        "motivation": "Financial",
        "active_since": "2013",
        "target_industries": ["Banking", "Finance", "Hospitality", "Retail"],
        "ttps": ["T1566.001", "T1059.003", "T1056.001", "T1070", "T1486"],
        "known_malware": ["Carbanak", "Cobalt Strike", "GCMAN"],
        "description": "Pioneered large-scale bank heist operations by living inside bank networks for months to learn operations, then manipulating ATM dispensing software and SWIFT messaging. Stole over $1B from 100+ banks in 40 countries.",
        "recent_activity": "Low Activity",
    },
    {
        "id": "nobelium_2024",
        "name": "Midnight Blizzard",
        "aliases": ["APT29 2024 Campaign", "Nobelium"],
        "origin": "Russia",
        "sponsor": "SVR",
        "motivation": "Espionage",
        "active_since": "2024",
        "target_industries": ["Technology", "Government", "Defense", "Political"],
        "ttps": ["T1566.001", "T1078.004", "T1550.001", "T1021.002"],
        "known_malware": ["GraphicalNeutrino", "WellMess variants"],
        "description": "APT29's 2024 campaign targeting Microsoft corporate emails (executives) and subsequently other technology companies. Used password spray attacks then OAuth token theft to maintain persistent access to email inboxes.",
        "recent_activity": "Active",
    },
    {
        "id": "salt_typhoon",
        "name": "Salt Typhoon",
        "aliases": ["FamousSparrow", "GhostEmperor", "Earth Estries"],
        "origin": "China",
        "sponsor": "MSS",
        "motivation": "Espionage",
        "active_since": "2020",
        "target_industries": ["Telecom", "Government", "Technology", "ISP"],
        "ttps": ["T1190", "T1078", "T1021.001", "T1040", "T1505.003"],
        "known_malware": ["SparrowDoor", "ShadowPad", "Demodex rootkit"],
        "description": "Chinese APT that compromised major US telecommunications carriers (AT&T, Verizon, T-Mobile) in 2024, wiretapping senior US government officials and court-authorized surveillance targets in one of the most significant intelligence breaches in US history.",
        "recent_activity": "Active",
    },
    {
        "id": "medusa",
        "name": "Medusa",
        "aliases": ["Medusa Blog"],
        "origin": "Unknown (likely Eastern Europe)",
        "sponsor": "Cybercriminal",
        "motivation": "Financial",
        "active_since": "2022",
        "target_industries": ["Healthcare", "Education", "Government", "Finance", "Manufacturing"],
        "ttps": ["T1566.001", "T1190", "T1486", "T1078", "T1021.001"],
        "known_malware": ["Medusa ransomware"],
        "description": "Ransomware group targeting critical infrastructure. FBI/CISA advisory (March 2025) warned of 300+ victims across critical sectors. Uses legitimate remote access tools and disables security software before deploying ransomware.",
        "recent_activity": "Active",
    },
    {
        "id": "earth_lusca",
        "name": "Earth Lusca",
        "aliases": ["TAG-22", "Charcoal Typhoon"],
        "origin": "China",
        "sponsor": "I-SOON (MSS contractor)",
        "motivation": "Espionage",
        "active_since": "2019",
        "target_industries": ["Government", "Telecom", "Research", "Healthcare", "Media"],
        "ttps": ["T1190", "T1059.001", "T1078", "T1027", "T1105"],
        "known_malware": ["ShadowPad", "Cobalt Strike", "SpiderControl"],
        "description": "Chinese APT linked to I-SOON (leaked contractor documents 2024). Conducts espionage against governments in Southeast Asia, South Asia, and Taiwan. Also performs financially motivated attacks.",
        "recent_activity": "Active",
    },
    {
        "id": "ransomed_vc",
        "name": "Ransomed.vc",
        "aliases": ["Ransomedvc"],
        "origin": "Unknown",
        "sponsor": "Cybercriminal",
        "motivation": "Financial",
        "active_since": "2023",
        "target_industries": ["Technology", "Media", "Entertainment"],
        "ttps": ["T1566.001", "T1190", "T1486", "T1537"],
        "known_malware": ["Custom ransomware variants"],
        "description": "Emerging ransomware group that breached Sony (2023) and claimed multiple high-profile victims. Known for fraudulent GDPR violation claims — threatening victims with regulatory reporting as additional extortion leverage.",
        "recent_activity": "Low Activity",
    },
]


async def seed_threat_actors():
    """Populate the threat_actors table if it is empty."""
    from db import database as db
    existing = await db.get_threat_actors()
    if existing:
        return len(existing)
    count = 0
    for actor in THREAT_ACTORS:
        await db.upsert_threat_actor(actor)
        count += 1
    return count
