"""
CMMC 2.0 Level 2 — all 110 practices aligned to NIST SP 800-171 Rev 2.
"""

CMMC_PRACTICES = [
    # ── Access Control (AC) ─────────────────────────────────────────────────
    {"id": "AC.L2-3.1.1",  "domain": "Access Control",        "title": "Authorized Access Control", "description": "Limit system access to authorized users, processes, and devices."},
    {"id": "AC.L2-3.1.2",  "domain": "Access Control",        "title": "Transaction & Function Control", "description": "Limit system access to the types of transactions and functions authorized users are permitted to execute."},
    {"id": "AC.L2-3.1.3",  "domain": "Access Control",        "title": "Control CUI Flow", "description": "Control the flow of CUI in accordance with approved authorizations."},
    {"id": "AC.L2-3.1.4",  "domain": "Access Control",        "title": "Separation of Duties", "description": "Separate the duties of individuals to reduce the risk of malevolent activity."},
    {"id": "AC.L2-3.1.5",  "domain": "Access Control",        "title": "Least Privilege", "description": "Employ the principle of least privilege, including for specific security functions and privileged accounts."},
    {"id": "AC.L2-3.1.6",  "domain": "Access Control",        "title": "Non-Privileged Account Use", "description": "Use non-privileged accounts or roles when accessing non-security functions."},
    {"id": "AC.L2-3.1.7",  "domain": "Access Control",        "title": "Privileged Functions", "description": "Prevent non-privileged users from executing privileged functions and capture the execution in audit logs."},
    {"id": "AC.L2-3.1.8",  "domain": "Access Control",        "title": "Unsuccessful Logon Attempts", "description": "Limit unsuccessful logon attempts."},
    {"id": "AC.L2-3.1.9",  "domain": "Access Control",        "title": "Privacy & Security Notices", "description": "Provide privacy and security notices consistent with CUI rules."},
    {"id": "AC.L2-3.1.10", "domain": "Access Control",        "title": "Session Lock", "description": "Use session lock with pattern-hiding displays after a period of inactivity."},
    {"id": "AC.L2-3.1.11", "domain": "Access Control",        "title": "Session Termination", "description": "Terminate sessions after a defined condition."},
    {"id": "AC.L2-3.1.12", "domain": "Access Control",        "title": "Control Remote Access", "description": "Monitor and control remote access sessions."},
    {"id": "AC.L2-3.1.13", "domain": "Access Control",        "title": "Remote Access Confidentiality", "description": "Employ cryptographic mechanisms to protect confidentiality of remote access sessions."},
    {"id": "AC.L2-3.1.14", "domain": "Access Control",        "title": "Remote Access Routing", "description": "Route remote access via managed access control points."},
    {"id": "AC.L2-3.1.15", "domain": "Access Control",        "title": "Privileged Remote Access", "description": "Authorize remote execution of privileged commands and access of security-relevant info via remote access only for documented operational needs."},
    {"id": "AC.L2-3.1.16", "domain": "Access Control",        "title": "Wireless Access Authorization", "description": "Authorize wireless access prior to allowing connections."},
    {"id": "AC.L2-3.1.17", "domain": "Access Control",        "title": "Wireless Access Protection", "description": "Protect wireless access using authentication and encryption."},
    {"id": "AC.L2-3.1.18", "domain": "Access Control",        "title": "Mobile Device Connection", "description": "Control connection of mobile devices."},
    {"id": "AC.L2-3.1.19", "domain": "Access Control",        "title": "Encrypt CUI on Mobile", "description": "Encrypt CUI on mobile devices and mobile computing platforms."},
    {"id": "AC.L2-3.1.20", "domain": "Access Control",        "title": "External System Connections", "description": "Verify and control connections to external systems."},
    {"id": "AC.L2-3.1.21", "domain": "Access Control",        "title": "Portable Storage Use", "description": "Limit use of portable storage devices on external systems."},
    {"id": "AC.L2-3.1.22", "domain": "Access Control",        "title": "Control Public Information", "description": "Control CUI posted or processed on publicly accessible systems."},
    # ── Awareness & Training (AT) ───────────────────────────────────────────
    {"id": "AT.L2-3.2.1",  "domain": "Awareness & Training",  "title": "Role-Based Risk Awareness", "description": "Ensure that personnel are aware of the security risks associated with their activities."},
    {"id": "AT.L2-3.2.2",  "domain": "Awareness & Training",  "title": "Role-Based Training", "description": "Ensure personnel are trained to carry out assigned security responsibilities."},
    {"id": "AT.L2-3.2.3",  "domain": "Awareness & Training",  "title": "Insider Threat Awareness", "description": "Provide security awareness training on recognizing and reporting potential insider threats."},
    # ── Audit & Accountability (AU) ─────────────────────────────────────────
    {"id": "AU.L2-3.3.1",  "domain": "Audit & Accountability", "title": "System Auditing", "description": "Create and retain system audit logs to enable monitoring, analysis, investigation, and reporting."},
    {"id": "AU.L2-3.3.2",  "domain": "Audit & Accountability", "title": "User Accountability", "description": "Ensure that the actions of individual users can be traced to those users."},
    {"id": "AU.L2-3.3.3",  "domain": "Audit & Accountability", "title": "Event Review", "description": "Review and update logged events."},
    {"id": "AU.L2-3.3.4",  "domain": "Audit & Accountability", "title": "Audit Failure Alerting", "description": "Alert in the event of an audit logging process failure."},
    {"id": "AU.L2-3.3.5",  "domain": "Audit & Accountability", "title": "Audit Correlation", "description": "Correlate audit record review, analysis, and reporting processes."},
    {"id": "AU.L2-3.3.6",  "domain": "Audit & Accountability", "title": "Reduction & Reporting", "description": "Provide audit record reduction and report generation to support analysis."},
    {"id": "AU.L2-3.3.7",  "domain": "Audit & Accountability", "title": "Authoritative Time Source", "description": "Provide a system capability that compares and synchronizes internal clocks."},
    {"id": "AU.L2-3.3.8",  "domain": "Audit & Accountability", "title": "Audit Protection", "description": "Protect audit information and tools from unauthorized access, modification, and deletion."},
    {"id": "AU.L2-3.3.9",  "domain": "Audit & Accountability", "title": "Audit Management", "description": "Limit management of audit logging to a subset of privileged users."},
    # ── Configuration Management (CM) ──────────────────────────────────────
    {"id": "CM.L2-3.4.1",  "domain": "Configuration Management", "title": "System Baselining", "description": "Establish and maintain baseline configurations and inventories of organizational systems."},
    {"id": "CM.L2-3.4.2",  "domain": "Configuration Management", "title": "Security Configuration Enforcement", "description": "Establish and enforce security configuration settings for IT products."},
    {"id": "CM.L2-3.4.3",  "domain": "Configuration Management", "title": "Configuration Change Control", "description": "Track, review, approve, and log changes to organizational systems."},
    {"id": "CM.L2-3.4.4",  "domain": "Configuration Management", "title": "Security Impact Analysis", "description": "Analyze the security impact of changes prior to implementation."},
    {"id": "CM.L2-3.4.5",  "domain": "Configuration Management", "title": "Access Restrictions for Change", "description": "Define, document, approve, and enforce physical and logical access restrictions."},
    {"id": "CM.L2-3.4.6",  "domain": "Configuration Management", "title": "Least Functionality", "description": "Employ the principle of least functionality by configuring systems to provide only essential capabilities."},
    {"id": "CM.L2-3.4.7",  "domain": "Configuration Management", "title": "Nonessential Functionality", "description": "Restrict, disable, or prevent the use of nonessential programs, functions, ports, protocols, and services."},
    {"id": "CM.L2-3.4.8",  "domain": "Configuration Management", "title": "Application Execution Policy", "description": "Apply deny-by-exception policy to prevent use of unauthorized software."},
    {"id": "CM.L2-3.4.9",  "domain": "Configuration Management", "title": "User-Installed Software", "description": "Control and monitor user-installed software."},
    # ── Identification & Authentication (IA) ───────────────────────────────
    {"id": "IA.L2-3.5.1",  "domain": "Identification & Authentication", "title": "User Identification", "description": "Identify information system users, processes, and devices."},
    {"id": "IA.L2-3.5.2",  "domain": "Identification & Authentication", "title": "User Authentication", "description": "Authenticate users, processes, or devices as a prerequisite to system access."},
    {"id": "IA.L2-3.5.3",  "domain": "Identification & Authentication", "title": "Multifactor Authentication", "description": "Use multifactor authentication for local and network access to privileged and non-privileged accounts."},
    {"id": "IA.L2-3.5.4",  "domain": "Identification & Authentication", "title": "Replay-Resistant Authentication", "description": "Employ replay-resistant authentication mechanisms for network access."},
    {"id": "IA.L2-3.5.5",  "domain": "Identification & Authentication", "title": "Identifier Reuse", "description": "Employ the principle of least privilege, including for specific security functions and privileged accounts."},
    {"id": "IA.L2-3.5.6",  "domain": "Identification & Authentication", "title": "Identifier Handling", "description": "Disable identifiers after a defined inactivity period."},
    {"id": "IA.L2-3.5.7",  "domain": "Identification & Authentication", "title": "Password Complexity", "description": "Enforce a minimum password complexity and change requirements."},
    {"id": "IA.L2-3.5.8",  "domain": "Identification & Authentication", "title": "Password Reuse", "description": "Prohibit password reuse for a specified number of generations."},
    {"id": "IA.L2-3.5.9",  "domain": "Identification & Authentication", "title": "Temporary Passwords", "description": "Allow temporary password use for system logons with immediate change requirement."},
    {"id": "IA.L2-3.5.10", "domain": "Identification & Authentication", "title": "Cryptographically-Protected Passwords", "description": "Store and transmit only cryptographically-protected passwords."},
    {"id": "IA.L2-3.5.11", "domain": "Identification & Authentication", "title": "Obscure Feedback", "description": "Obscure feedback of authentication information."},
    # ── Incident Response (IR) ──────────────────────────────────────────────
    {"id": "IR.L2-3.6.1",  "domain": "Incident Response",     "title": "Incident Handling", "description": "Establish an operational incident-handling capability including preparation, detection, analysis, containment, recovery, and user response activities."},
    {"id": "IR.L2-3.6.2",  "domain": "Incident Response",     "title": "Incident Reporting", "description": "Track, document, and report incidents to designated officials and/or authorities."},
    {"id": "IR.L2-3.6.3",  "domain": "Incident Response",     "title": "Incident Response Testing", "description": "Test the organizational incident response capability."},
    # ── Maintenance (MA) ────────────────────────────────────────────────────
    {"id": "MA.L2-3.7.1",  "domain": "Maintenance",           "title": "Perform Maintenance", "description": "Perform maintenance on organizational systems."},
    {"id": "MA.L2-3.7.2",  "domain": "Maintenance",           "title": "System Maintenance Control", "description": "Provide controls on the tools, techniques, mechanisms, and personnel used to conduct maintenance."},
    {"id": "MA.L2-3.7.3",  "domain": "Maintenance",           "title": "Equipment Sanitization", "description": "Ensure equipment removed for maintenance is sanitized."},
    {"id": "MA.L2-3.7.4",  "domain": "Maintenance",           "title": "Media Inspection", "description": "Check media containing diagnostic and test programs for malicious code before use."},
    {"id": "MA.L2-3.7.5",  "domain": "Maintenance",           "title": "Nonlocal Maintenance", "description": "Require MFA for remote maintenance sessions and disconnect after use."},
    {"id": "MA.L2-3.7.6",  "domain": "Maintenance",           "title": "Maintenance Personnel", "description": "Supervise maintenance activities of personnel without required access authorization."},
    # ── Media Protection (MP) ───────────────────────────────────────────────
    {"id": "MP.L2-3.8.1",  "domain": "Media Protection",      "title": "Media Protection", "description": "Protect (i.e., physically control and securely store) system media containing CUI."},
    {"id": "MP.L2-3.8.2",  "domain": "Media Protection",      "title": "Media Access", "description": "Limit access to CUI on system media to authorized users."},
    {"id": "MP.L2-3.8.3",  "domain": "Media Protection",      "title": "Media Sanitization", "description": "Sanitize or destroy information system media before disposal or reuse."},
    {"id": "MP.L2-3.8.4",  "domain": "Media Protection",      "title": "Media Marking", "description": "Mark media with necessary CUI markings and distribution limitations."},
    {"id": "MP.L2-3.8.5",  "domain": "Media Protection",      "title": "Media Accountability", "description": "Control access to media containing CUI and maintain accountability for media."},
    {"id": "MP.L2-3.8.6",  "domain": "Media Protection",      "title": "Portable Storage Encryption", "description": "Implement cryptographic mechanisms to protect CUI during transport unless protected by alternative physical safeguards."},
    {"id": "MP.L2-3.8.7",  "domain": "Media Protection",      "title": "Removable Media", "description": "Control the use of removable media on system components."},
    {"id": "MP.L2-3.8.8",  "domain": "Media Protection",      "title": "Shared Media", "description": "Prohibit the use of portable storage devices when such devices have no identifiable owner."},
    {"id": "MP.L2-3.8.9",  "domain": "Media Protection",      "title": "CUI Backup Protection", "description": "Protect the confidentiality of backup CUI at storage locations."},
    # ── Personnel Security (PS) ─────────────────────────────────────────────
    {"id": "PS.L2-3.9.1",  "domain": "Personnel Security",    "title": "Screen Individuals", "description": "Screen individuals prior to authorizing access to organizational systems containing CUI."},
    {"id": "PS.L2-3.9.2",  "domain": "Personnel Security",    "title": "Personnel Actions", "description": "Ensure CUI is protected during and after personnel actions such as terminations and transfers."},
    # ── Physical Protection (PE) ────────────────────────────────────────────
    {"id": "PE.L2-3.10.1", "domain": "Physical Protection",   "title": "Limit Physical Access", "description": "Limit physical access to organizational systems to authorized individuals."},
    {"id": "PE.L2-3.10.2", "domain": "Physical Protection",   "title": "Monitor Physical Access", "description": "Protect and monitor the physical facility and support infrastructure."},
    {"id": "PE.L2-3.10.3", "domain": "Physical Protection",   "title": "Escort Visitors", "description": "Escort visitors and monitor visitor activity."},
    {"id": "PE.L2-3.10.4", "domain": "Physical Protection",   "title": "Physical Access Logs", "description": "Maintain audit logs of physical access."},
    {"id": "PE.L2-3.10.5", "domain": "Physical Protection",   "title": "Manage Physical Access", "description": "Control and manage physical access devices."},
    {"id": "PE.L2-3.10.6", "domain": "Physical Protection",   "title": "Alternative Work Sites", "description": "Enforce safeguarding measures for CUI at alternate work sites."},
    # ── Risk Assessment (RA) ────────────────────────────────────────────────
    {"id": "RA.L2-3.11.1", "domain": "Risk Assessment",       "title": "Risk Assessments", "description": "Periodically assess the risk to operations, assets, and individuals."},
    {"id": "RA.L2-3.11.2", "domain": "Risk Assessment",       "title": "Vulnerability Scan", "description": "Scan for vulnerabilities in organizational systems periodically and when new vulnerabilities are identified."},
    {"id": "RA.L2-3.11.3", "domain": "Risk Assessment",       "title": "Vulnerability Remediation", "description": "Remediate vulnerabilities in accordance with risk assessments."},
    # ── Security Assessment (CA) ────────────────────────────────────────────
    {"id": "CA.L2-3.12.1", "domain": "Security Assessment",   "title": "Security Control Assessment", "description": "Periodically assess the security controls to determine if effective."},
    {"id": "CA.L2-3.12.2", "domain": "Security Assessment",   "title": "Plan of Action", "description": "Develop and implement plans of action to correct deficiencies."},
    {"id": "CA.L2-3.12.3", "domain": "Security Assessment",   "title": "Security Control Monitoring", "description": "Monitor security controls on an ongoing basis."},
    {"id": "CA.L2-3.12.4", "domain": "Security Assessment",   "title": "System Security Plan", "description": "Develop, document, and periodically update system security plans."},
    # ── System & Communications Protection (SC) ────────────────────────────
    {"id": "SC.L2-3.13.1",  "domain": "System & Comm Protection", "title": "Boundary Protection", "description": "Monitor, control, and protect communications at external boundaries."},
    {"id": "SC.L2-3.13.2",  "domain": "System & Comm Protection", "title": "Security Engineering", "description": "Employ architectural designs, software development techniques, and systems engineering principles."},
    {"id": "SC.L2-3.13.3",  "domain": "System & Comm Protection", "title": "Role Separation", "description": "Separate user functionality from system management functionality."},
    {"id": "SC.L2-3.13.4",  "domain": "System & Comm Protection", "title": "Shared Resource Control", "description": "Prevent unauthorized and unintended information transfer via shared system resources."},
    {"id": "SC.L2-3.13.5",  "domain": "System & Comm Protection", "title": "Public-Access System Separation", "description": "Implement subnetworks for publicly accessible system components separated from internal networks."},
    {"id": "SC.L2-3.13.6",  "domain": "System & Comm Protection", "title": "Network Communication by Exception", "description": "Deny network communications traffic by default."},
    {"id": "SC.L2-3.13.7",  "domain": "System & Comm Protection", "title": "Split Tunneling", "description": "Prevent remote devices from simultaneously connecting to both the system and other resources."},
    {"id": "SC.L2-3.13.8",  "domain": "System & Comm Protection", "title": "Data in Transit", "description": "Implement cryptographic mechanisms to prevent unauthorized disclosure of CUI during transmission."},
    {"id": "SC.L2-3.13.9",  "domain": "System & Comm Protection", "title": "Connections Termination", "description": "Terminate network connections after a defined period of inactivity."},
    {"id": "SC.L2-3.13.10", "domain": "System & Comm Protection", "title": "Key Management", "description": "Establish and manage cryptographic keys."},
    {"id": "SC.L2-3.13.11", "domain": "System & Comm Protection", "title": "CUI Encryption", "description": "Employ FIPS-validated cryptography to protect CUI."},
    {"id": "SC.L2-3.13.12", "domain": "System & Comm Protection", "title": "Collaborative Computing", "description": "Prohibit remote activation of collaborative computing and provide indication to users."},
    {"id": "SC.L2-3.13.13", "domain": "System & Comm Protection", "title": "Mobile Code", "description": "Control and monitor the use of mobile code."},
    {"id": "SC.L2-3.13.14", "domain": "System & Comm Protection", "title": "VoIP", "description": "Control and monitor the use of VoIP technologies."},
    {"id": "SC.L2-3.13.15", "domain": "System & Comm Protection", "title": "Communications Authenticity", "description": "Protect the authenticity of communications sessions."},
    {"id": "SC.L2-3.13.16", "domain": "System & Comm Protection", "title": "Data at Rest", "description": "Protect CUI at rest."},
    # ── System & Information Integrity (SI) ────────────────────────────────
    {"id": "SI.L2-3.14.1", "domain": "System & Info Integrity", "title": "Flaw Remediation", "description": "Identify, report, and correct information and information system flaws."},
    {"id": "SI.L2-3.14.2", "domain": "System & Info Integrity", "title": "Malicious Code Protection", "description": "Provide protection from malicious code at appropriate locations."},
    {"id": "SI.L2-3.14.3", "domain": "System & Info Integrity", "title": "Security Alerts", "description": "Monitor system security alerts and take appropriate action."},
    {"id": "SI.L2-3.14.4", "domain": "System & Info Integrity", "title": "Update Malicious Code Protection", "description": "Update malicious code protection mechanisms."},
    {"id": "SI.L2-3.14.5", "domain": "System & Info Integrity", "title": "System & File Scanning", "description": "Perform periodic scans and real-time scans of files from external sources."},
    {"id": "SI.L2-3.14.6", "domain": "System & Info Integrity", "title": "Security Monitoring", "description": "Monitor systems to detect attacks and indicators of potential attacks."},
    {"id": "SI.L2-3.14.7", "domain": "System & Info Integrity", "title": "Identify Unauthorized Use", "description": "Identify unauthorized use of organizational systems."},
]

DOMAIN_ORDER = [
    "Access Control",
    "Awareness & Training",
    "Audit & Accountability",
    "Configuration Management",
    "Identification & Authentication",
    "Incident Response",
    "Maintenance",
    "Media Protection",
    "Personnel Security",
    "Physical Protection",
    "Risk Assessment",
    "Security Assessment",
    "System & Comm Protection",
    "System & Info Integrity",
]

PRACTICE_LOOKUP = {p["id"]: p for p in CMMC_PRACTICES}
